apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app.kubernetes.io/instance":"influxdb","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"influxdb2"},"name":"influxdb-influxdb2-longhorn","namespace":"monitoring"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"storageClassName":"longhorn"}}
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: influxdb2
  name: influxdb-influxdb2-longhorn
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-62764c38-c40b-480c-a942-f34d64dca32c
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
