apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  k8s-local.server: |
    k8s.local:53 {
        errors
        health
        ready
        file /etc/coredns/shared/k8s.local.db {
          reload 10s
        }
        prometheus :9153
        cache 30
    }
