---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coredns-external-dns
  namespace: kube-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/coredns-external
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coredns-external-dns
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
