apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coredns-external-dns
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
