apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - args:
        - --source=service
        - --provider=rfc2136
        - --txt-owner-id=k3s-cluster
        - --domain-filter=k8s.local
        - --label-filter=external-dns=managed
        - --log-level=debug
        - --policy=sync
        - --registry=txt
        - --txt-prefix=external-
        - --interval=3m
        - --rfc2136-host=kube-dns.kube-system.svc.cluster.local
        - --rfc2136-port=53
        - --rfc2136-zone=k8s.local
        - --rfc2136-insecure
        image: registry.k8s.io/external-dns/external-dns:v0.13.1
        name: external-dns
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccountName: external-dns
