apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: nginx.k8s.local
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"external-dns.alpha.kubernetes.io/enabled":"true","external-dns.alpha.kubernetes.io/hostname":"nginx.k8s.local"},"name":"nginx-test","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"nginx"},"type":"ClusterIP"}}
  creationTimestamp: "2025-03-09T00:36:03Z"
  name: nginx-test
  namespace: default
  resourceVersion: "240407"
  uid: ac8c5080-fc45-4665-9084-49681b7dc9ad
spec:
  clusterIP: 10.43.195.217
  clusterIPs:
  - 10.43.195.217
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
