apiVersion: v1
kind: Pod
metadata:
  name: dns-updater
  namespace: kube-system
spec:
  containers:
  - name: dns-updater
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      cp /configmap/k8s.internal.db /dns-zone/k8s.internal.db && 
      echo "Zone file updated" && 
      sleep 3600
    volumeMounts:
    - name: configmap-volume
      mountPath: /configmap
    - name: dns-zone-volume
      mountPath: /dns-zone
  volumes:
  - name: configmap-volume
    configMap:
      name: k8s-internal-db
  - name: dns-zone-volume
    persistentVolumeClaim:
      claimName: coredns-zone-pvc
