apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: portainer.k8s.internal
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"portainer","namespace":"portainer"},"spec":{"loadBalancerIP":"192.168.1.20","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":9000},{"name":"https","port":443,"protocol":"TCP","targetPort":9443},{"name":"edge","port":30776,"protocol":"TCP","targetPort":8000}],"selector":{"app":"portainer"},"type":"LoadBalancer"}}
    metallb.io/ip-allocated-from-pool: default-pool
  name: portainer
  namespace: portainer
spec:
  allocateLoadBalancerNodePorts: true
  - 10.43.182.206
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.1.20
  ports:
  - name: http
    nodePort: 32068
    port: 80
    protocol: TCP
    targetPort: 9000
  - name: https
    nodePort: 31548
    port: 443
    protocol: TCP
    targetPort: 9443
  - name: edge
    nodePort: 31409
    port: 30776
    protocol: TCP
    targetPort: 8000
  selector:
    app: portainer
  sessionAffinity: None
  type: LoadBalancer
  loadBalancer:
    ingress:
    - ip: 192.168.1.20
      ipMode: VIP
