apiVersion: v1
kind: Pod
metadata:
  name: check-zone-file
  namespace: kube-system
spec:
  containers:
  - name: check-zone-file
    image: busybox
    command: ["/bin/sh", "-c", "cat /etc/coredns/shared/k8s.local.db && sleep 60"]
    volumeMounts:
    - name: coredns-zone
      mountPath: /etc/coredns/shared
  volumes:
  - name: coredns-zone
    persistentVolumeClaim:
      claimName: coredns-zone-pvc
  restartPolicy: Never
