apiVersion: v1
kind: Pod
metadata:
  name: check-zone-file
  namespace: kube-system
spec:
  restartPolicy: Never
  containers:
  - name: check-zone-file
    image: busybox
    command: ["sh", "-c", "cat /data/k8s.local.db && sleep 10"]
    volumeMounts:
    - name: zone-data
      mountPath: /data
  volumes:
  - name: zone-data
    persistentVolumeClaim:
      claimName: coredns-zone-pvc
