apiVersion: v1
kind: Pod
metadata:
  name: create-zone-dir
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: master-node
  containers:
  - name: create-zone-dir
    image: busybox
    command: ["sh", "-c", "mkdir -p /hostpath/var/lib/coredns-zone && chmod 777 /hostpath/var/lib/coredns-zone && echo 'Directory created successfully'"]
    volumeMounts:
    - name: hostpath
      mountPath: /hostpath
  volumes:
  - name: hostpath
    hostPath:
      path: /
      type: Directory
