apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
  namespace: homebridge
  labels:
    app: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      containers:
      - name: homebridge
        image: oznu/homebridge:latest
        ports:
        - containerPort: 8581
          name: web-ui
        - containerPort: 51827
          name: homekit
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: HOMEBRIDGE_CONFIG_UI
          value: "1"
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: "8581"
        volumeMounts:
        - name: homebridge-data
          mountPath: /homebridge
      volumes:
      - name: homebridge-data
        persistentVolumeClaim:
          claimName: homebridge-data
