apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  selector:
    app: homebridge
  ports:
  - name: web-ui
    port: 80
    targetPort: 8581
  - name: homekit
    port: 51827
    targetPort: 51827
  type: LoadBalancer
