apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-ssd
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  nodePath: /mnt/ssd
  # Use the ssd-config ConfigMap defined below
  configMapName: local-path-ssd-config
