apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-ssd-config
  namespace: kube-system
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/var/lib/rancher/k3s/storage"]
        },
        {
          "node":"worker1",
          "paths":["/mnt/ssd"]
        },
        {
          "node":"worker2",
          "paths":["/mnt/ssd"]
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -e
    mkdir -p ${VOLUME_PATH}
  teardown: |-
    #!/bin/sh
    set -e
    rm -rf ${VOLUME_PATH}
