apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
  name: portainer
  namespace: portainer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: portainer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - args:
        - --http-enabled
        image: portainer/portainer-ce:2.27.3
        imagePullPolicy: IfNotPresent
        name: portainer
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 8000
          name: edge
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: portainer-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: portainer-sa
      serviceAccountName: portainer-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: portainer-data
        persistentVolumeClaim:
          claimName: portainer-longhorn
  availableReplicas: 1
  conditions:
    lastUpdateTime: "2025-03-30T03:24:04Z"
    message: ReplicaSet "portainer-7db48769cc" has successfully progressed.
    reason: NewReplicaSetAvailable
    type: Progressing
    lastUpdateTime: "2025-03-30T19:54:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    type: Available
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
