apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: CoreDNS
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 1.1.1.1 8.8.8.8  # Cloudflare and Google DNS
        cache 30
        loop
        reload
        loadbalance
    }
  NodeHosts: |
    # Add your node IPs and hostnames here in the format:
    # 192.168.1.10 worker-node1
    # 192.168.1.11 worker-node2
