apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: CoreDNS
data:
  # Add your custom configurations here
  # Example: custom zones, upstream servers, etc.
  example.hosts: |
    # Add your custom host entries here, for example:
    # 10.0.0.1 example.local
    # 10.0.0.2 service.example.local
    
  # You can reference these files in the Corefile by adding:
  # in the main ConfigMap by modifying the CoreFile with something like:
  #
  # example.local {
  #   hosts /etc/coredns/custom/example.hosts
  # }
