apiVersion: v1
data:
  example.zone: |
    $ORIGIN example.com.
    $TTL 86400
    @       IN      SOA     ns1.example.com. hostmaster.example.com. (
                          2023032701 ; serial
                          3600       ; refresh
                          1800       ; retry
                          604800     ; expire
                          86400 )    ; minimum

    @       IN      NS      ns1.example.com.
    ns1     IN      A       192.168.1.10
    www     IN      A       192.168.1.20
    mail    IN      A       192.168.1.30

    _http._tcp      IN      SRV     0 5 80 www.example.com.
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"example.zone":"$ORIGIN example.com.\n$TTL 86400\n@       IN      SOA     ns1.example.com. hostmaster.example.com. (\n                      2023032701 ; serial\n                      3600       ; refresh\n                      1800       ; retry\n                      604800     ; expire\n                      86400 )    ; minimum\n\n@       IN      NS      ns1.example.com.\nns1     IN      A       192.168.1.10\nwww     IN      A       192.168.1.20\nmail    IN      A       192.168.1.30\n\n_http._tcp      IN      SRV     0 5 80 www.example.com.\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"example-zone-file","namespace":"kube-system"}}
  name: example-zone-file
  namespace: kube-system
