apiVersion: v1
data:
  k8s-internal.server: |
    k8s.internal:53 {
      file /etc/coredns/shared/k8s.internal.db
      errors
      log
      reload 10s
    }
  k8s.internal.db: |
    $ORIGIN k8s.internal.
    $TTL 3600
    @       IN      SOA     ns1.k8s.internal. admin.k8s.internal. (
                                1743380128 ; serial
                                7200       ; refresh
                                3600       ; retry
                                1209600    ; expire
                                3600 )     ; minimum

            IN      NS      ns1.k8s.internal.
    ns1     IN      A       127.0.0.1

    ; MetalLB Services
    adguard         IN      A       192.168.1.25
    adguard2        IN      A       192.168.1.26
    traefik         IN      A       192.168.1.23
    dashboard       IN      A       192.168.1.24
    longhorn        IN      A       192.168.1.21
    fluentbit       IN      A       192.168.1.33
    grafana         IN      A       192.168.1.30
    influxdb        IN      A       192.168.1.29
    portainer       IN      A       192.168.1.20
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"k8s-internal.server":"k8s.internal:53 {\n  file /etc/coredns/shared/k8s.internal.db\n  errors\n  log\n  reload 10s\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"k8s-internal-zone","namespace":"kube-system"}}
  name: k8s-internal-zone
  namespace: kube-system
