apiVersion: v1
data:
  k8s-internal.server: |
    k8s.internal:53 {
        file /etc/coredns/shared/k8s.internal.db k8s.internal
        errors
        log
        reload 10s
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  name: k8s-internal-server
  namespace: kube-system
