apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Los_Angeles
        - name: HOMEBRIDGE_CONFIG_UI
          value: "1"
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: "8581"
        image: homebridge/homebridge:latest
        imagePullPolicy: Always
        name: homebridge
        ports:
        - containerPort: 8581
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: /homebridge
          name: homebridge-data
      volumes:
      - name: homebridge-data
        persistentVolumeClaim:
          claimName: homebridge-data
