apiVersion: apps/v1
kind: Deployment
metadata:
  name: cups
  namespace: cups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cups
  template:
    metadata:
      labels:
        app: cups
    spec:
      containers:
      - name: cups
        image: ydkn/cups:latest
        # Remove the explicit command
        ports:
        - containerPort: 631
          name: cups
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/cups
          name: cups-config
        - mountPath: /var/lib/cups
          name: cups-data
        - mountPath: /var/log/cups
          name: cups-logs
        - mountPath: /dev/bus/usb
          name: usb
        - mountPath: /run/avahi-daemon
          name: avahi-run
      volumes:
      - name: cups-config
        emptyDir: {}
      - name: cups-data
        persistentVolumeClaim:
          claimName: cups-data
      - name: cups-logs
        emptyDir: {}
      - name: usb
        hostPath:
          path: /dev/bus/usb
      - name: avahi-run
        emptyDir: {}
