apiVersion: batch/v1
kind: Job
metadata:
  name: install-ipp-usb
  namespace: cups
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node2
      restartPolicy: Never
      hostNetwork: true
      hostPID: true
      containers:
      - name: installer
        image: debian:bullseye
        command:
        - /bin/bash
        - -c
        - |
          apt-get update
          apt-get install -y ipp-usb
          
          # Enable and start the service
          systemctl enable ipp-usb
          systemctl start ipp-usb
          
          # Check status
          echo "Service status:"
          systemctl status ipp-usb
          
          # List USB devices
          echo "USB devices:"
          lsusb
        securityContext:
          privileged: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: Exists
