apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipp-usb-daemon
  namespace: cups
spec:
  selector:
    matchLabels:
      app: ipp-usb
  template:
    metadata:
      labels:
        app: ipp-usb
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node2
      hostNetwork: true
      hostPID: true
      containers:
      - name: ipp-usb
        image: ubuntu:22.04
        command:
        - /bin/bash
        - -c
        - |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y ipp-usb usbutils iputils-ping
          
          # List USB devices to identify the printer
          echo "Available USB devices:"
          lsusb
          
          # Run ipp-usb
          echo "Starting ipp-usb daemon..."
          ipp-usb
          
          # Keep the container running to continuously handle USB printer connections
          echo "ipp-usb daemon started, container will now stay running..."
          while true; do
            sleep 60
            echo "ipp-usb daemon is running. Checking USB devices:"
            lsusb | grep DYMO
          done
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-usb
          mountPath: /dev/bus/usb
        - name: etc-cups
          mountPath: /etc/cups
      volumes:
      - name: dev-usb
        hostPath:
          path: /dev/bus/usb
      - name: etc-cups
        hostPath:
          path: /etc/cups
