---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --source=service
        - --source=ingress
        - --provider=coredns
        - --domain-filter=k8s.local
        - --policy=upsert-only
        - --log-level=debug
        - --txt-prefix=external-dns-
        - --coredns-prefix=k8s
        volumeMounts:
        - name: coredns-zone
          mountPath: /etc/coredns
      securityContext:
        fsGroup: 65534
      volumes:
      - name: coredns-zone
        persistentVolumeClaim:
          claimName: coredns-zone-pvc
