apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-custom
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns-custom
  template:
    metadata:
      labels:
        app: external-dns-custom
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: bitnami/kubectl:latest
        command: ["/bin/sh"]
        args: ["-c", "cp /scripts/update-dns.sh /tmp/ && chmod +x /tmp/update-dns.sh && /tmp/update-dns.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: coredns-zone
          mountPath: /etc/coredns/shared
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: scripts
        configMap:
          name: external-dns-script
      - name: coredns-zone
        persistentVolumeClaim:
          claimName: coredns-zone-pvc
      securityContext:
        fsGroup: 65534
