apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/YOUR-GITHUB-USER/k3s-cluster.git"
    targetRevision: HEAD
    path: apps/adguard  # This must match the folder in your Git repo
    helm:
      values: |
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.1.32
        persistence:
          enabled: true
          existingClaim: adguard-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
