apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      url: http://influxdb-influxdb2:8086
      jsonData:
        version: Flux
        organization: influxdata
      secureJsonData:
        token: KP5DmiOssnh0yzh0Wg6WYqZDAIIi4lqX
      isDefault: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"datasources.yaml":"apiVersion: 1\ndatasources:\n- name: InfluxDB\n  type: influxdb\n  access: proxy\n  url: http://influxdb-influxdb2:8086\n  jsonData:\n    version: Flux\n    organization: influxdata\n  secureJsonData:\n    token: KP5DmiOssnh0yzh0Wg6WYqZDAIIi4lqX\n  isDefault: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"grafana"},"name":"grafana-datasources","namespace":"monitoring"}}
  labels:
    app.kubernetes.io/name: grafana
  name: grafana-datasources
  namespace: monitoring
