apiVersion: v1
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      allowUiUpdates: true
      editable: true
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"dashboardproviders.yaml":"apiVersion: 1\nproviders:\n- name: 'default'\n  orgId: 1\n  folder: ''\n  type: file\n  disableDeletion: false\n  allowUiUpdates: true\n  editable: true\n  updateIntervalSeconds: 10\n  options:\n    path: /var/lib/grafana/dashboards\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"environment":"production"},"name":"grafana-provider-config","namespace":"monitoring"}}
  labels:
    environment: production
  name: grafana-provider-config
  namespace: monitoring
