apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: local:p-8zbt8
    lifecycle.cattle.io/create.namespace-auth: "true"
    management.cattle.io/no-default-sa-token: "true"
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQvU7DQBCEXwVtfTHYluP4JFoaWiTq9d0kOXI/lm+dFJbfHR00FIDS7Uoz8+3OSgHCloVJr8QxJmFxKeaypvEDRjKkml2qDIt4VC49Okuabmm+5IkNSP0pTLeIeXe6XkhT4MgnBET5Ibi26uHVRfv84gF5vzsycgBpOhbXzuLIi5e7TN/xmmhTZGZ8/frmArJwmEjHxXtFnkf4fxs4cz6Tph49uOkbPsB2A9eG9+C6O/Rm7Dq7H9qxHdr6qSm0X0/eFOUJhvRaJmFZCnbbPgMAAP//qGc0XpcBAAA
    objectset.rio.cattle.io/id: workspace
    objectset.rio.cattle.io/owner-gvk: management.cattle.io/v3, Kind=FleetWorkspace
    objectset.rio.cattle.io/owner-name: fleet-default
    objectset.rio.cattle.io/owner-namespace: ""
  finalizers:
  - controller.cattle.io/namespace-auth
  labels:
    field.cattle.io/projectId: p-8zbt8
    kubernetes.io/metadata.name: fleet-default
    objectset.rio.cattle.io/hash: 7e7ea272a8ed59a1ca6ea1587cb55d693b393102
  name: fleet-default
spec:
  finalizers:
  - kubernetes
  phase: Active
